### ISSUE TITLE
Build System Bug: cmake fails if you don't have g++ installed

### ISSUE THREAD

**Issue by gatesphere** [stevedekorte/io#165]
Hi all, found this small bug that causes cmake to fail if you don't have g++ installed.

Env: Solaris 11 x86
gcc installed, g++ not.

output of cmake ..
    -- Detecting C compiler ABI info - done
    CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
    -- Configuration set to: DebugFast
    -- GMP libs: /usr/lib/libgmp.so /usr/lib/libgmpxx.so

Fix: install g++.  I don't know cmake enough, or I would have attached a patch that fixes this in the build system rather than adding another package to the system.

-->Jake

**Comment by apjanke** [comment]
Might be a little more complex than just declaring the project language type. Some of the addons and extras use C++.

```
$ find . -name '*.cpp'
./addons/SoundTouch/source/SoundTouch_wrapper.cpp
./addons/Loki/samples/shootout/C/nsieve-bits/nsieve-bits.cpp
./addons/Loki/samples/shootout/C/nsieve/nsieve.cpp
./extras/symbian/SymbianSockets.cpp
./extras/symbian/symbianmain.cpp
```

However: addons/SoundTouch doesn't have a `CMakeLists.txt` file. And the `nsieve.cpp` and `nsieve-bits.cpp` files under Loki are simple; they don't need to be C++ and it would be straightforward to convert them to plain C. (In fact, one of them looks like it already is plain C.)

Still care about this?

**Comment by apjanke** [comment]
Wait, nevermind: those `samples/shootout` files are not actually compiled as part of the main Io project. Switching it to C should be straightforward after all.

**Comment by apjanke** [comment]
Patch: #384
