### ISSUE TITLE
Redundant union members in IoObject_struct.h

### ISSUE THREAD

**Issue by kmag** [stevedekorte/io#197]
Currently in head in https://github.com/stevedekorte/io/blob/master/libs/iovm/source/IoObject_struct.h

IoObjectData contains:

union
    {
        union
        {
            void *ptr;
            void *ptr2;
        } pointers;
        double d;
        uint32_t ui32;
    } data; // 8 bytes (9+8 = 17)

ptr and ptr2 have the same type and occupy the same space.  The names seem to imply the intention was to use them as a cons cell, or at least be able to use both ptr and ptr simultaneously.

On #io today, jer had a look and it doesn't appear that IoObject_dataPointer2 is used anywhere.  ptr2 should probably be removed along with pointers, and ptr placed directly in data.  There's no performance or space savings, but it gets rid of a potential source of subtle bugs.

**Comment by AlesTsurko** [comment]
@stevedekorte mention you to note your attention — looks like you can close this issue.

**Comment by stevedekorte** [comment]
thanks Ales
