### ISSUE TITLE
Cairo

### ISSUE THREAD

**Issue by adams164** [stevedekorte/io#205]
Line 82 of "IoCairoFontOptions.c":
 'proto' should be 'protoId'

**Comment by AlesTsurko** [comment]
This one is fixed as we can see with the above reference to https://github.com/stevedekorte/io/commit/ace681c8238b6b97b812ce9ff753c458506004aa
@stevedekorte could you close it please?

**Comment by stevedekorte** [comment]
yes, thanks Ales
