### ISSUE TITLE
install_path not set on OS X builds

### ISSUE THREAD

**Issue by ghost** [stevedekorte/io#224]
When Io is compiled with build.sh with a modified INSTALL_PREFIX, the install_path is not set.

After compiling for /usr/sw,

    $ otool -D /usr/sw/lib/libbasekit.dylib
    /usr/sw/lib/libbasekit.dylib:
    libbasekit.dylib

meaning the run-time linker will look only in the default place, which of course causes this:

    $ io
    dyld: Library not loaded: libbasekit.dylib
      Referenced from: /usr/sw/bin/io
      Reason: image not found
    Trace trap

Setting DYLD_LIBRARY_PATH of course fixes this, but aside from being a hack, corrupts the search path. I have copies of libraries shipped as parts of Apple's system frameworks in /usr/sw/lib, and /usr/sw/lib's appearance in DYLD_LIBRARY_PATH causes them to be loaded before the copy in the framework's Resources folder. As they are missing symbols, the framework will not load. This causes problems in Io, when e.g. the OpenGL module is loaded, which pulls in several system frameworks.

I do not know if the rpath on other systems is affected, or how CMake handles either setting.

**Comment by indyjo** [comment]
I recently modified the CMake build to use @rpath-relative  install names for the libraries. Does that fix/affect your problem? (See commit fbf6cd2667fa7509a71d23c8f634f9416477176c)
