### ISSUE TITLE
Sequence does not respond to ':'

### ISSUE THREAD

**Issue by liuqingshan** [stevedekorte/io#259]
Hi Sir:

I wrote a program in  file (e.g named test.io) , as follows:

OperatorTable addAssignOperator(":", "test")

test := method( 
   writeln("test")		
)

"foo" : "bar"

Open a terminal run：
    io test.io 

result is:
  
  Exception: Sequence does not respond to ':'
  ---------
  Sequence :                           test.io 7
  CLI doFile                           Z_CLI.io 140
  CLI run                              IoState_runCLI() 1

I can not find the cause of the error, please help, thank U!

Enviroments:
    OS : 21-Ubuntu SMP Tue Nov 12 17:07:40 UTC 2013 i686 i686 i686 GNU/Linux
    Io version: 20110905 
    Io download from http://iobin.suspended-chord.info/linux/iobin-linux-x86-deb-current.zip

**Comment by 7hi4g0** [comment]
Why doesn't OperatorTable addAssignOperator() isn't applied within the source file where it is called?

Is that intended behaviour or is it a non implemented feature?

**Comment by stevedekorte** [comment]
It's because that file has to be parsed before it can be run.
