### ISSUE TITLE
Should Io have a logo?

### ISSUE THREAD

**Issue by rtoal** [stevedekorte/io#289]
Seems like a nice-to-have, but only if the language designer agrees. Ioke and Fancy have them....

**Comment by joedf** [comment]
:+1:

**Comment by PedroBatista** [comment]
The visual image of letters:  Io (sans serif) is my choice for a logo.

2015-01-12 18:25 GMT+00:00 Joe DF <notifications@github.com>:

**Comment by joedf** [comment]
![0001](https://cloud.githubusercontent.com/assets/3848219/5710178/dcbf5d68-9a6d-11e4-8938-de845a8b6e85.png)

**Comment by dethtron5000** [comment]
Really quick idea - please feel free to use, modify or throw away.  The idea is to retain the black and white aesthetic already established by the language site and to imply the message passing mechanics used in the language along with a representation of the I and the O.
![iologo](https://cloud.githubusercontent.com/assets/952341/5711465/c8ed2e90-9a78-11e4-93d1-e91941660ffb.png)

**Comment by stevedekorte** [comment]
Thanks to everyone here for the suggestions. I'm glad to see people taking an interest in helping out. 
I'd be interested to hear your thoughts on the current logo:
http://upload.wikimedia.org/wikipedia/commons/2/26/Io-logo.svg

**Comment by joedf** [comment]
Seems fine :+1:
Just thought that we were aiming for something more "playful" ?

**Comment by pankajdoharey** [comment]
I think it should have a logo i was trying to write an IO implementation in ruby and i thought logo for io would be a cool idea. 

I named my implementation 'Esha' after a girl i know here's the logo i designed for it : https://github.com/pankajdoharey/Esha

**Comment by shevegen** [comment]
I like the idea behind  joedf's one; it's a bit too unreadable, but perhaps the idea could be combined into the one by steve - so that Io is visible, but there is some circle around it

**Comment by codymoorhouse** [comment]
I like joedf's logo, its simple but pretty cool, the current logo looks a bit bland and predated
