### ISSUE TITLE
Performance for simple calculation

### ISSUE THREAD

**Issue by kokizzu** [stevedekorte/io#292]
First of all, seriously IO syntax is so beautiful ^___^)b
But the performance is not quite good, or maybe my code has bug?

I tried to create a simple program to calculate odd prime number, print the prime number every 10K-th found and exit after 10M found:
```
last := 3
res := List clone append(last)
loop(
   last = last + 2
   prime := true
   res foreach(i, v, 
      if(v*v > last, break)
      if(last%v == 0, 
      	 prime = false
      	 break
      )
   ) 
   if(prime,
   	  res append(last)
   	  if(res size % 100000 == 0, last println)
   	  if(last>9999999, break)
   )
)
```

For comparison, other [languages/implementation](kokizzu.blogspot.com/2015/03/prime-number-generator-benchmark.html) can complete the calculation within a minute.

**Comment by stevedekorte** [comment]
Hi kokizzu,

Io's number objects are true dynamic objects and not meant for number crunching as that code will allocate a huge number of objects. I suggest using a few Vector objects (which deal with native numbers efficiently and using SIMD instructions) and writing this as vectorized code or using a vectorized algorithm to accomplish the same goal.

**Comment by stevedekorte** [comment]
e.g. here's some code for vectorized calculation of a Mandlebrot set in Io: 

https://github.com/stevedekorte/io/blob/master/samples/shootout/mandelbrot.io

**Comment by kokizzu** [comment]
still, quite slow..
```
last := 3
#res := List clone append(last)
res := Sequence clone setItemType("int32") setEncoding("number") # just this part right?
res append(last)
loop(
   last = last + 2
   prime := true
   res foreach(i, v, 
      if(v*v > last, break)
      if(last%v == 0, 
      	 prime = false
      	 break
      )
   ) 
   if(prime,
   	  res append(last)
   	  if(res size % 100000 == 0, last println)
   	  if(last>9999999, break)
   )
)
```

**Comment by stevedekorte** [comment]
Your code is not vectorized and is still producing a vast number of new object allocations. I'm not sure about the best way to vectorize a prime number search but I'll try to show how to avoid the extra allocations.

**Comment by stevedekorte** [comment]
I guess we could do this pretty quickly if there was a Sequence fmod denominator method.
