### ISSUE TITLE
Comparison methods generation.

### ISSUE THREAD

**Issue by akhramov** [stevedekorte/io#293]
IRC and mailing list seem dead, so I will ask my question here. 

According to [guide](http://iolanguage.org/scm/io/docs/IoGuide.html#Control-Flow) I need to implement `compare()` method in order to get comparison methods (like ==, < , >, etc). Suppose I want to compare dogs by their size. Well, I wrote `compare()` method but something is wrong anyway. What am I doing wrong? Thanks in advance.

```IO
Dog := Object clone
 
Dog size := 0
Dog compare := method(anotherDog, self size compare(anotherDog size))
 
evil := Dog clone
 
evil == Dog # false for some reasons
evil compare(Dog) # 0 as expected, though
```

**Comment by stevedekorte** [comment]
Sorry for the confusion. The docs are wrong on this. It looks like == is a C primitive method that calls the Object isEquals() primitive method directly. Overriding == should work around this.

**Comment by akhramov** [comment]
Thanks for an answer. I really like this language anyway!
