### ISSUE TITLE
Encoded lists with nil don't round trip properly

### ISSUE THREAD

**Issue by brosander** [stevedekorte/io#306]
Nil values appear to be dropped from the end of lists when they're decoded.  This can result in a complete failure when reading fromEncodedList:

    Io> List fromEncodedList(list(nil) asEncodedList)
    
      Exception: Io Assertion 'unrecognized encoded type'
      ---------
      message 'fromEncodedList' in 'Command Line' on line 1

**Comment by brosander** [comment]
This is from a master build as of fb9098698e8e54e6d03dbfdd68b1d37ced7d1b20

**Comment by brosander** [comment]
Built from master as of https://github.com/stevedekorte/io/tree/fb9098698e8e54e6d03dbfdd68b1d37ced7d1b20

**Comment by peterhull90** [comment]
I believe this issue can also be closed.
