### ISSUE TITLE
Misleading/outdated/missing information about alternative implementations on the iolanguage.org website.

### ISSUE THREAD

**Issue by JoergWMittag** [stevedekorte/io#310]
At the bottom of the [Io Language website](http://iolanguage.org/), there are currently three alternative implementations listed:

* PyPy &rarr; https://bitbucket.org/pypy/lang-io
* CLR &rarr; http://io.codeplex.com/
* JVM &rarr; http://ioke.org/

However, the PyPy one is [abandoned](https://bitbucket.org/pypy/lang-io/issues/1/read-me) and will most likely not even build with current versions of PyPy and RPython, if it ever did.

The binary that can be [downloaded](http://io.codeplex.com/releases/view/26252) for the CLR implementation actually works (at least kind of), but neither the binary nor the source repository have been touched in over 7 years (the name of the release is "September 2008", even if it was released in 2009). [The link to the company website](http://synrc.com/research/io/index.htm) is dead, and there is no mention of Io either on the [website](http://synrc.com/) or the company's [GitHub repositories](https://github.com/synrc/). The project looks abandoned.

Ioke is not an implementation of Io, it's a different programming language. Plus, the project is abandoned.

I recommend removing all three links, and thus the entire section.

In fact, all projects for alternative implementations of Io I found have either been abandoned (e.g. [Callisto (on Rubinius)](https://github.com/dwaite/Callisto), Mentis (on Rubinius), [Europa (in Go)](https://github.com/saysjonathan/europa), even your own [oia (in ECMAScript)](https://github.com/stevedekorte/oia)) or morphed into a different language (e.g. [Acute (originally a meta-circular implementation of Io-in-Io, now a different language)](https://github.com/acutelanguage/acute), which for bonus points additionally also belongs into the "abandoned" category as well).

---

Note: I dont know whether filing issues about the website here is appropriate, but I couldn't find a better venue. Feel free to ignore, close, and burn.

**Comment by stevedekorte** [comment]
Hi Joerg,

I understand this can be frustrating. The links were meant as "further reading" notes and not to imply the projects were active. I guess a note about that might be helpful. Thanks for the feedback.

**Comment by JoergWMittag** [comment]
Hi Steve, 

thanks for getting back to me in person, and sorry for not getting back to you earlier.

Don't get me wrong, I'm not frustrated. I'm more annoyed, but by myself: this is something I noticed years ago, and was always too lazy to do something about.

I'm a bit of a language geek, so, "further reading" material is kinda my thing! I actually became aware of both Io and Ioke at around the same time, and watched Ola Bini give talks on Ioke, in which he never neglected to give credit to you and Io for inspiring him to design Ioke, so, I was kind of surprised to see Ioke described as "an implementation of Io" on your website. That's kinda like calling Io an implementation of JavaScript (grossly exaggerated), especially since CommonLisp and Ruby are at least as big an influence on Ioke as Io is.

Anyway, what I *really* wanted to say to put this issue to rest: I like the new site!

**Comment by stevedekorte** [comment]
I'm glad you like it :)

Yeah, sorry for the confusion. I didn't look into Ioke closely and wasn't aware that it was so different. I think I'll add a section of "related projects" on the links page with pointers to those other languages and implementations. How does that sound?
