### ISSUE TITLE
Build failure on Fedora 23+

### ISSUE THREAD

**Issue by limburgher** [stevedekorte/io#316]
Trying to build 2015.11.11 on Fedora (I'm the package maintainer) and it's failing in garbagecollector:

 33%] Linking C shared library _build/dll/libgarbagecollector.so
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_size.localalias.6':
CollectorMarker.c:(.text+0x0): multiple definition of `List_size'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x0): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_ifNeededSizeTo_.localalias.5':
CollectorMarker.c:(.text+0x12): multiple definition of `List_ifNeededSizeTo_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x12): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_rawAt_':
CollectorMarker.c:(.text+0x51): multiple definition of `List_rawAt_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x51): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_at_.localalias.4':
CollectorMarker.c:(.text+0x74): multiple definition of `List_at_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x74): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_indexOf_':
CollectorMarker.c:(.text+0xc9): multiple definition of `List_indexOf_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0xc9): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_contains_':
CollectorMarker.c:(.text+0x134): multiple definition of `List_contains_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x134): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_append_.localalias.3':
CollectorMarker.c:(.text+0x19e): multiple definition of `List_append_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x19e): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_appendSeq_':
CollectorMarker.c:(.text+0x200): multiple definition of `List_appendSeq_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x200): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_compactIfNeeded.localalias.2':
CollectorMarker.c:(.text+0x26c): multiple definition of `List_compactIfNeeded'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x26c): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_removeIndex_.localalias.1':
CollectorMarker.c:(.text+0x2b3): multiple definition of `List_removeIndex_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x2b3): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_removeIndex_toIndex_':
CollectorMarker.c:(.text+0x34d): multiple definition of `List_removeIndex_toIndex_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x34d): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_remove_.localalias.0':
CollectorMarker.c:(.text+0x423): multiple definition of `List_remove_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x423): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_removeFirst_':
CollectorMarker.c:(.text+0x481): multiple definition of `List_removeFirst_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x481): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_removeLast_':
CollectorMarker.c:(.text+0x4f2): multiple definition of `List_removeLast_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x4f2): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_removeItems_':
CollectorMarker.c:(.text+0x522): multiple definition of `List_removeItems_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x522): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_at_insert_':
CollectorMarker.c:(.text+0x58e): multiple definition of `List_at_insert_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x58e): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_at_put_':
CollectorMarker.c:(.text+0x65f): multiple definition of `List_at_put_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x65f): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_swap_with_':
CollectorMarker.c:(.text+0x6c7): multiple definition of `List_swap_with_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x6c7): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_reverseInPlace':
CollectorMarker.c:(.text+0x759): multiple definition of `List_reverseInPlace'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x759): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_push_':
CollectorMarker.c:(.text+0x7a6): multiple definition of `List_push_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x7a6): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_pop':
CollectorMarker.c:(.text+0x805): multiple definition of `List_pop'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x805): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_top':
CollectorMarker.c:(.text+0x868): multiple definition of `List_top'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x868): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_removeTrueFor_':
CollectorMarker.c:(.text+0x8a3): multiple definition of `List_removeTrueFor_'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x8a3): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_qsort':
CollectorMarker.c:(.text+0x963): multiple definition of `List_qsort'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x963): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_qsort_r':
CollectorMarker.c:(.text+0x999): multiple definition of `List_qsort_r'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x999): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_bsearch':
CollectorMarker.c:(.text+0x9da): multiple definition of `List_bsearch'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0x9da): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_first':
CollectorMarker.c:(.text+0xa17): multiple definition of `List_first'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0xa17): first defined here
CMakeFiles/garbagecollector.dir/source/CollectorMarker.o: In function `List_last':
CollectorMarker.c:(.text+0xa36): multiple definition of `List_last'
CMakeFiles/garbagecollector.dir/source/Collector.o:Collector.c:(.text+0xa36): first defined here
/usr/bin/ld: cannot find -lbasekit
collect2: error: ld returned 1 exit status
CMakeFiles/garbagecollector.dir/build.make:120: recipe for target '_build/dll/libgarbagecollector.so' failed
make[2]: *** [_build/dll/libgarbagecollector.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/garbagecollector.dir/all' failed
make[1]: *** [CMakeFiles/garbagecollector.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Warning messages from cmake . in the garbagecollector folder include:

The dependency target "basekit" of target "garbagecollector" does not
  exist.

This also occurred with 2013.12.04.

Thanks!

**Comment by pileon** [comment]
I get the same problem in Ubuntu 15.10.

Works fine on an older (but otherwise up-to-date) Debian 7 installation though.

**Comment by peterhull90** [comment]
I suspect this is caused by the change of GCC 4 to GCC 5 and the corresponding change of C standard from gnu90 to gnu11. This changed the behaviour of `inline`.
As a workround you can get back the old behaviour. I modified `build.sh` to add `-DCMAKE_C_FLAGS="--std=gnu90"` to the cmake command (line 27) and that built for me on Fedora 23 x64.
The real solution is to update the code in `Common_inline.h` - I can have a look if no-one wants to but it looks a bit tricky!

**Comment by peterhull90** [comment]
I've put in a pull request #319 for discussion/testing. Thanks!

**Comment by peterhull90** [comment]
@limburgher Did this work for you? Also your builds may be affected by #320 for your i686 targets, might be work checking out.

**Comment by limburgher** [comment]
It did, but I had to disable SIMD.  Patch attached.

On Fri, Jan 29, 2016 at 6:14 AM, Peter Hull <notifications@github.com>
wrote:

> @limburgher <https://github.com/limburgher> Did this work for you? Also
> your builds may be affected by #320
> <https://github.com/stevedekorte/io/issues/320> for your i686 targets,
> might be work checking out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevedekorte/io/issues/316#issuecomment-176725570>.
>



-- 
http://cecinestpasunefromage.wordpress.com/
------------------------------------------------
in your fear, seek only peace
in your fear, seek only love

-d. bowie

**Comment by peterhull90** [comment]
No patch! But I assume it's the one from this page.
https://apps.fedoraproject.org/packages/Io-language/sources/patches/
This is the same as I reported in #320. Would it be possible for you to try the latest code that includes PR #321? I think this should fix the problem without disabling SIMD. I'd appreciate any feedback, thanks.

**Comment by limburgher** [comment]
On Fri, Jan 29, 2016 at 9:28 AM, Peter Hull <notifications@github.com>
wrote:

> No patch! But I assume it's the one from this page.
> https://apps.fedoraproject.org/packages/Io-language/sources/patches/
> This is the same as I reported in #320
> <https://github.com/stevedekorte/io/issues/320>. Would it be possible for
> you to try the latest code that includes PR #321
> <https://github.com/stevedekorte/io/pull/321>? I think this should fix
> the problem without disabling SIMD. I'd appreciate any feedback, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevedekorte/io/issues/316#issuecomment-176813948>.
>
It was this:

--- libs/basekit/source/UArray_math.c~  2016-01-24 12:59:28.000000000 -0500
+++ libs/basekit/source/UArray_math.c   2016-01-25 11:07:08.635258429 -0500
@@ -7,7 +7,7 @@
 #include <math.h>
 #include <float.h>

-#define IO_USE_SIMD 1
+//#define IO_USE_SIMD 1

 #ifdef IO_USE_SIMD

The code in the 321 does fix the 32-bit x86 built, but the ARM build is
still broken, so we'll have to remain with SIMD disabled.


-- 
http://cecinestpasunefromage.wordpress.com/
------------------------------------------------
in your fear, seek only peace
in your fear, seek only love

-d. bowie
