### ISSUE TITLE
#327 mistakenly closed please reopen

### ISSUE THREAD

**Issue by wirser** [stevedekorte/io#329]
I added a comment to issue 327 and mistakenly closed it sorrry

**Comment by stevedekorte** [comment]
What was it called? I'm having a hard time getting github search to find it or to even list all closed issued :/

**Comment by wirser** [comment]
This is the issue I am referring to .today I was able to access it after clicking on the open issues then the closed list was avaiable
 unable to compile unbuntu 13.04 86_64 relatedto #247 #327
    wirser opened this Issue 17 days ago · 3 comments

**Comment by stevedekorte** [comment]
Ok, reopened. I should have just set the URL to that issue number :)
