### ISSUE TITLE
libs/basekit/source/UArray.c:851]: (error) Memory leak: out

### ISSUE THREAD

**Issue by dcb314** [stevedekorte/io#336]
Source code is

    UArray *out = UArray_new();
    UArray *convertedOther = other;

    if (itemCount == 0)
    {
        UArray_error_(self, "UArray_insert_every_: itemCount must be > 0");
        return;
    }

**Comment by stevedekorte** [comment]
Thanks dcb314. Would you like to submit a pull request?

**Comment by dcb314** [comment]
You are welcome. I have no idea what a pull request is, but I
suspect you are asking me to fix the bug in some way.

I just find them. Someone with far more knowledge of the code
is in a better position to fix it.

**Comment by stevedekorte** [comment]
In this case, it looks like:

UArray *out = UArray_new();
UArray *convertedOther = other;

if (itemCount == 0)
{
    UArray_free(out);
    UArray_error_(self, "UArray_insert_every_: itemCount must be > 0");
    return;
}

How did you find the memory leak?

**Comment by dcb314** [comment]
>In this case, it looks like:

In my view, it doesn't look good because some new memory 
might be soon freed. 

How about sanity checking parameters first and then if ok, going on to grab memory ?

>How did you find the memory leak?

Static analysis tool called cppcheck, available from sourceforge. 
I find it really useful for C/C++ code, along with valgrind for
dynamic analysis.

**Comment by stevedekorte** [comment]
Yeah, I didn't look at the actual method but alloc after check makes sense. Sanity checks are the responsibility of the classes new and free methods.
