### ISSUE TITLE
Sequence does not respond to 'findRegex'

### ISSUE THREAD

**Issue by kmein** [stevedekorte/io#338]
I've written a small script to pull down a webpage and then extract something via regex. If I, however, match the result of `URL with(…) fetch` using `findRegex`, the Exception mentioned in the issue title is thrown.

The solution seems to be to do something with the `Regex` library first, like explicitly instantiating the regex pattern using `Regex with(…)`. But then the output of my script is cluttered with `Registering Regex: Regex`.

Is there some way around that?

**Comment by piotrklibert** [comment]
No, you need to only reference `Regex` (no need to call anything) on top of your script. This will make the loader try to find and load a file where `Regex` is defined.  The `findRegex` method is probably added to Sequence in the same file, so it's absent if you don't load the file.

The same is true for example for `to` method on Numbers - you need to load Range for the method to be added.

**Comment by AlesTsurko** [comment]
@stevedekorte this can be closed. As of the message, I'll make a PR.
