### ISSUE TITLE
make failure on MacBook Pro (Retina, 13-inch, Early 2015), macos 10.12.2

### ISSUE THREAD

**Issue by guxingke** [stevedekorte/io#344]
version : [58d7a6](https://github.com/stevedekorte/io/commit/58d7a69d33d1e260eb10b759b37726e5e02f90f3)

error log 
```
[ 95%] Building C object addons/UUID/CMakeFiles/IoUUID.dir/source/IoUUID.c.o
In file included from /Users/gxk/toy/io/io/addons/UUID/source/IoUUID.c:17:
In file included from /Users/gxk/toy/io/io/addons/UUID/source/IoUUID.h:11:
In file included from /Users/gxk/toy/io/io/libs/iovm/source/IoObject.h:243:
In file included from /Users/gxk/toy/io/io/libs/iovm/source/IoObject_inline.h:12:
In file included from /Users/gxk/toy/io/io/libs/iovm/source/IoState.h:23:
In file included from /Users/gxk/toy/io/io/libs/iovm/source/IoCoroutine.h:12:
In file included from /Users/gxk/toy/io/io/libs/coroutine/source/Coro.h:75:
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:47:29: error: field has incomplete type 'struct user64_sigaltstack'
        struct user64_sigaltstack       uc_stack;       /* stack */
                                        ^
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:47:9: note: forward declaration of 'struct user64_sigaltstack'
        struct user64_sigaltstack       uc_stack;       /* stack */
               ^
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:56:29: error: field has incomplete type 'struct user32_sigaltstack'
        struct user32_sigaltstack       uc_stack;       /* stack */
                                        ^
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:56:9: note: forward declaration of 'struct user32_sigaltstack'
        struct user32_sigaltstack       uc_stack;       /* stack */
               ^
2 errors generated.
make[2]: *** [addons/UUID/CMakeFiles/IoUUID.dir/source/IoUUID.c.o] Error 1
make[1]: *** [addons/UUID/CMakeFiles/IoUUID.dir/all] Error 2
make: *** [all] Error 2
```

help me , thanks

**Comment by piotrklibert** [comment]
I had the same problem on my mac; it's been ages since I worked with C and quick google didn't help, so I just disabled the UUID Addon. You can do this by commenting out this line: https://github.com/stevedekorte/io/blob/master/addons/CMakeLists.txt#L116 and rebuilding Io.

The interesting thing is that Homebrew manages to build Io with the UUID Addon, I didn't have the time to investigate (and frankly, I don't need this particular Addon very much), but maybe @cielavenir would know how to fix this properly.

Also, I had problems with SecureSocket Addon where it looked like ssl and crypto libraries were not found, but this may be specific to my system. I fixed this by changing `SecureSocket/CMakeLists.txt` to manually add ssl and crypto libraries as I was sure they are there, however the proper fix would be to make CMake able to find the correct ssl lib. I didn't have the time to investigate, unfortunately.

**Comment by guxingke** [comment]
Thanks. @piotrklibert, follow your step , it build succeed.

**Comment by stevedekorte** [comment]
A pull request for the fix would be appreciated :)

**Comment by apjanke** [comment]
This is a tricky one. The compiler complaint is about a system header `sys/ucontext.h`. But that's used by the Io coroutine library, which is pulled in in multiple places, so why is it just the UUID addon that's breaking?

Using `make VERBOSE=1 2>&1 | tee make.out`, we can see the full details of the build. Here's the actual failing command in the UUID plugin.

```
[ 94%] Building C object addons/UUID/CMakeFiles/IoUUID.dir/source/IoUUID.c.o
cd /Users/janke/local/repos/io/build/addons/UUID && /Applications/Xcode-9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DIoUUID_EXPORTS -I/Users/janke/local/repos/io/libs/coroutine/source -I/Users/janke/local/repos/io/libs/basekit/source -I/Users/janke/local/repos/io/libs/garbagecollector/source -I/Users/janke/local/repos/io/libs/iovm/source -I/System/Library/Frameworks/Kernel.framework/Headers  -msse2 -g -O0 -fPIC   -o CMakeFiles/IoUUID.dir/source/IoUUID.c.o   -c /Users/janke/local/repos/io/addons/UUID/source/IoUUID.c
In file included from /Users/janke/local/repos/io/addons/UUID/source/IoUUID.c:17:
In file included from /Users/janke/local/repos/io/addons/UUID/source/IoUUID.h:11:
In file included from /Users/janke/local/repos/io/libs/iovm/source/IoObject.h:243:
In file included from /Users/janke/local/repos/io/libs/iovm/source/IoObject_inline.h:12:
In file included from /Users/janke/local/repos/io/libs/iovm/source/IoState.h:23:
In file included from /Users/janke/local/repos/io/libs/iovm/source/IoCoroutine.h:12:
In file included from /Users/janke/local/repos/io/libs/coroutine/source/Coro.h:75:
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:47:29: error: field has incomplete type 'struct user64_sigaltstack'
        struct user64_sigaltstack       uc_stack;       /* stack */
                                        ^
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:47:9: note: forward declaration of 'struct user64_sigaltstack'
        struct user64_sigaltstack       uc_stack;       /* stack */
               ^
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:56:29: error: field has incomplete type 'struct user32_sigaltstack'
        struct user32_sigaltstack       uc_stack;       /* stack */
                                        ^
/System/Library/Frameworks/Kernel.framework/Headers/sys/ucontext.h:56:9: note: forward declaration of 'struct user32_sigaltstack'
        struct user32_sigaltstack       uc_stack;       /* stack */
               ^
2 errors generated.
make[2]: *** [addons/UUID/CMakeFiles/IoUUID.dir/source/IoUUID.c.o] Error 1
```

The thing that makes this different from the rest of the compilations in Io is that it's pulling in the Kernel framework with that `-I/System/Library/Frameworks/Kernel.framework/Headers`. I don't see anything else in the Io build doing that.

And that seems to be the issue. 

It looks like there are multiple variants of the `sys/ucontext.h` header: the one from the base system (at `/usr/include/sys/ucontext.h`), and the one from Kernel.framework, at least. And it seems that the one in Kernel.framework has an issue with incomplete type definitions.

Those `user32_sigaltstack` and `user64_sigaltstack` types were defined [in `sys/signal.h` in a previous version of Darwin](https://opensource.apple.com/source/xnu/xnu-3247.10.11/bsd/sys/signal.h?txt), but they don't seem to be there any more. In fact, I did a `grep` through my whole machine looking for them and came up empty. So this might actually be an issue with the Apple-supplied headers. I've filed a bug with Apple, radar ID 37494819.

So I think the question for Io is, how and why is the UUID addon pulling in Kernel.framework, when nothing else in Io is? I don't see anything obvious in the `CMakeLists` files.
