### ISSUE TITLE
All Network objects can't working.

### ISSUE THREAD

**Issue by Hypnoes** [stevedekorte/io#352]
I'm using windows10. Using .exe file download from [iolang.org](http://iolanguage.org/binaries.html).
This code is from [Io-lang:Networking](http://iolanguage.org/guide/guide.html#Primitives-Networking).
```Io
WebRequest := Object clone do(
    handleSocket := method(aSocket,
        aSocket streamReadNextChunk
        request := aSocket readBuffer \
			betweenSeq("GET ", " HTTP")
        f := File with(request) 
        if(f exists, 
			f streamTo(aSocket)
		, 
			aSocket streamWrite("not found")
		)
        aSocket close
    )
)

WebServer := Server clone do(
    setPort(8000)
    handleSocket := method(aSocket, 
        WebRequest clone asyncSend(handleSocket(aSocket))
    )
)

WebServer start
```
While 
```PowerShell
io .\webserver.io
```
It reply:
```
  Exception: Object does not respond to 'Server'
  ---------
  Object Server                        webserver.io 19
  CLI doFile                           Z_CLI.io 140
  CLI run                              IoState_runCLI() 1
```
It's not only the Server object, most of objects from [Networking](http://iolanguage.org/reference/index.html#Socket.DNS),
[Thread](http://iolanguage.org/reference/index.html#Thread.Thread), and many others packages? modules? (I'm not sure what it called.) cause this issues.
XD

**Comment by Hypnoes** [comment]
No one respond.  Sad...☹

**Comment by stevedekorte** [comment]
Sorry, I'm not on Windows. It should automatically load the Server/Socket library when it's referenced. I'd recommend posting this bug on the Io binary release repo: https://github.com/gatesphere/io-info

**Comment by mweichert** [comment]
This can be resolved by running:
`eerie install https://github.com/IoLanguage/Socket.git`
