### ISSUE TITLE
io Changes in Language

### ISSUE THREAD

**Issue by dc0d** [stevedekorte/io#355]
I wonder what changes are made to the language itself since 4-5 years ago?

I very much like to see io on Go - but there is no such thing or I failed to find it - and decided to play around the .NET port (https://github.com/devaspot/io) to see if I can make a Go version of it.

My current problems:
- I do not know anything about PLs internals (other than some theoretical & superficial bits about lexers and parsers)
- I think porting from C would produce a more performant implementation since the `*free` functions are there and can be used with Go's `sync.Pool` to do some memory optimizations and not relying on Go's GC too much - but it's not that important I guess.

io on Go benefits from Go's ecosystem (running on many architectures, GC, goroutines, delegating implementation of many things - http & http2, websockets, system interfaces, ... - to Go which is being actively developed and maintained etc etc) and the active atmosphere around it. So a io on Go implementation can focus on better tooling.

I posted this question here because apparently yahoo group is not maintained and I could not find any link to community. Please accept my apologies if it looks not much related to this context.

**Comment by stevedekorte** [comment]
Nothing significant has changed in the last 5 years. Goroutines would be nice to build on. Javascript's await() could also be used to implement coroutines, at least for a language built on top of JS.
