### ISSUE TITLE
Why 'true'/'false' does not respond to '&&' and '||'?

### ISSUE THREAD

**Issue by AlesTsurko** [stevedekorte/io#364]
I can see these operators with OperatorTable, but can't find where are they come from. The intuition tells me that they are similar to +=, *= etc. operators, that work only with vectors. But anyway... is it a bug or normal behaviour?:D

**Comment by stevedekorte** [comment]
It's normal. Io uses the and() and or() methods instead of sigils. For example:

    Io> true and(false)
    ==> false

    Io> true or(false)
    ==> true

You can define && and || them if you like:

    Object setSlot("&&", Object getSlot("and"))
    Object setSlot("||", Object getSlot("or"))

**Comment by AlesTsurko** [comment]
Thanks Steve! Yes, I know about ```and``` and ```or```, but what haunts me, is that I can see && and || in the operator table and it's unexpected that they're don't work out-of-the-box. Why are they there?
At the same time it's a part of Io, that I find a very cool — Vim-like "configure your own IDE", but for programming language. It's so inspiring! Thank you for that!

**Comment by stevedekorte** [comment]
They are there as standard default behaviors if people choose to use those operators.
