### ISSUE TITLE
How to extend existing addon with natively written methods?

### ISSUE THREAD

**Issue by AlesTsurko** [stevedekorte/io#368]
Hi @stevedekorte. 
I'm writing a markdown parser based on [discount](http://www.pell.portland.or.us/~orc/Code/discount/).
I would like to simplify things to just the only method `markdownToHTML`. And I'd like to call this method on a `Sequence` directly. But I can't find a way to extend `IoSeq` with a native (C) addon without changing Io's sources and recompiling the Io itself.

A simple function (a top level `method` for an `Object`) could be an alternative, if the above is impossible. I could use such function in Io code to extend `Sequence`. But again, how to extend `Object` with a method then?

I'm trying to achieve something like:

```Io
"# Hello" markdownToHTML // will return "<h1>Hello</h1>"
```

or

```Io
markdownToHTML("# Hello") // will return "<h1>Hello</h1>"
```

Could you please help with some advice or example?

**Comment by stevedekorte** [comment]
Hey Ales,

I'd recommend adding a Markdown addon with a Markdown primitive in it with your markdownToHTML method. Then add a .io file in your addon that contains something like:

Sequence markdownToHTML := method(aString, Markdown markdownToHTML(aString))

IIRC, the Blowfish addon does this. You might take a look at it.

**Comment by AlesTsurko** [comment]
Thanks. Done: https://github.com/AlesTsurko/Markdown
But there is an issue... I've spend the whole day trying to fix it. Sometimes the output is as if its was with wrong encoding. The problem lies somewhere in the conversion from `char*` to `uint8_t` (used in UArray for IoSeq's data). I had not programmed in C too much, so I've no idea how to fix it for now — just trying to make some random things...

**Comment by stevedekorte** [comment]
Yeah, Io's strings are always fixed length characters. You should be able to find some C methods to import UTF8 in there somewhere though.

**Comment by AlesTsurko** [comment]
Looks like `UArray_setCString_` does the trick. Thanks!
