### ISSUE TITLE
What is "attachedMessage" of Message in old sources?

### ISSUE THREAD

**Issue by AlesTsurko** [stevedekorte/io#371]
Hi Steve,

I'm trying to reanimate the Debugger example from Flux's samples. I've found the file `messageview.io`, that needed for this example. But there is a slot called `attachedMessage` used by `Message`. Looks like that was changed at some point in the past. I can't find any commit or source for this, even in the old fork. Could you explain what is `attachedMessage`?

**Comment by stevedekorte** [comment]
I think the name of that method was shortened to "attached".

**Comment by AlesTsurko** [comment]
But what is `attached` then? `previous`?

**Comment by stevedekorte** [comment]
Sorry, looks like I misremember that detail. Looking at the docs, it appears it was renamed to "next".

http://iolanguage.org/reference/index.html#Core.Message

**Comment by AlesTsurko** [comment]
There is `nextMessage` already... Here is the code: https://github.com/stevedekorte/io/blob/9a3cf2f05bf2c8475ee6ccc36d54d79ed9c6ce9a/addons/Flux/samples/Debugger/MessageView.io

**Comment by stevedekorte** [comment]
Hm, I'm guessing it was a convenience method to point to the next message in the chain after the next end-of-line message (a semicolon message).

Btw, in googling for this, I ran across: http://www.quantumg.net/iodebug/

**Comment by AlesTsurko** [comment]
Like this: `next nextIgnoreEndOfLines`?
When I've seen a screenshot I became motivated to fix it even more) I'll definitely return to this later.

**Comment by stevedekorte** [comment]
It looks like nextIgnoreEndOfLines returns the next message, skipping over endOfLine messages (returns and semicolons).
