### ISSUE TITLE
"non-existent dependency Foundation" warning on macOS

### ISSUE THREAD

**Issue by apjanke** [stevedekorte/io#379]
I'm building Io from the head of `master` at commit ba2c9d95, on macOS 10.13.3 with Xcode 9.2.

When I do a `mkdir build; cd build; cmake ..`, I get a warning about a non-existent dependency.

```

-- Configuring done
CMake Warning (dev) at addons/ObjcBridge/CMakeLists.txt:44 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "Foundation" of target "IoObjcBridge" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

```

Full `cmake` output: https://gist.github.com/apjanke/158d279337bc03507d65c6af231c97f1

I think [this](https://github.com/stevedekorte/io/blob/ba2c9d95f9f9a01025a23e46dcd1077a76a200a7/addons/ObjcBridge/CMakeLists.txt#L44) is where it's happening:

```
# Now build the shared library
add_library(IoObjcBridge SHARED ${SRCS})
add_dependencies(IoObjcBridge iovmall Foundation IoMD5 IoYajl IoBox IoSocket IoBlowfish IoSystemCall)
target_link_libraries(IoObjcBridge iovmall ${ObjcBridge_LIBRARY} IoMD5 IoYajl IoBox IoSocket IoBlowfish IoSystemCall /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit)
```

Foundation doesn't seem to be defined at that point.

The AppleSensors addon deals with Foundation slightly differently:

```

find_library(FOUNDATION Foundation)
if (IOKIT)
  #add_executable(IoAppleSensors ${program_SOURCES})

  # Now build the shared library
  add_library(IoAppleSensors SHARED ${SRCS})
  add_dependencies(IoAppleSensors iovmall)
  target_link_libraries(IoAppleSensors iovmall ${IOKIT} ${FOUNDATION})
```

This is a minor nuisance; I don't think it's breaking the build, and the "correctness" tests pass. But it could hinder working with later versions of CMake.

**Comment by stevedekorte** [comment]
Hey Andrew, thanks for the issue report. I'd welcome a patch if you have ideas on how to fix this.

**Comment by apjanke** [comment]
Here's a patch: #381. I believe this corrects the error, and brings `ObjcBridge` in line with how `addons/AppleSensors` is doing things.
