### ISSUE TITLE
Cannot find Freetype on macOS

### ISSUE THREAD

**Issue by apjanke** [stevedekorte/io#380]
I'm building Io from the head of `master` at commit ba2c9d95, on macOS 10.13.3 with Xcode 9.2.

I have Freetype installed under `/usr/local` (via Homebrew), but Io's `cmake` isn't finding it.

```
-- Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS) 
```

Full cmake output: https://gist.github.com/apjanke/158d279337bc03507d65c6af231c97f1

There's [a workaround in the Homebrew `io` formula](https://github.com/Homebrew/homebrew-core/blob/187bc28feb81558f231b0ad5f1ac28d99f8b17c9/Formula/io.rb#L57-L58), which suggests this issue has been there for a while.

I tried updating `modules/FindFreetype.cmake` with the one from the recent CMake 3.10.2 release, and it seemed to find Freetype okay. Maybe it should be updated in Io's build system? I'm not familiar enough with CMake to know how much of a chore/risk that is.

**Comment by stevedekorte** [comment]
I'm not very familiar with cmake either. Maybe you could ask Jeremy Tregunna on the Io mailing list? He implemented the cmake system.

**Comment by apjanke** [comment]
Sure. Uh, what's the mailing list? I don't see a link here or on http://iolanguage.org/, and Googling "io mailing list" isn't pulling up anything.

Here's an example PR for discussion and testing purposes: #382.

**Comment by stevedekorte** [comment]
Might be better to ask Jer on Twitter: https://twitter.com/jtregunna?lang=en

**Comment by jeremytregunna** [comment]
@apjanke Hey, I currently don't have a macOS machine anymore, but I can take a look at this in a VM on linux by putting it in other places. Let me twiddle on this see if I can reproduce it and go from there.

**Comment by apjanke** [comment]
Great. Thanks.

And if an upgrade like this is legit, you might want to do `FindOpenSSL`, too, to support custom OpenSSL install locations: https://github.com/stevedekorte/io/pull/392.

**Comment by anargiros12** [comment]
Lolauance
