### ISSUE TITLE
Move Io's site to github pages

### ISSUE THREAD

**Issue by ales-tsurko** [stevedekorte/io#415]
Hi Steve,

What do you think about moving the site to github pages? It'd allow others contribute to Io's website and made changes in there faster. 
This issue also relevant to https://github.com/IoLanguage/io/issues/414

**Comment by stevedekorte** [comment]
I think that's a great idea. I'll look into it now.

**Comment by stevedekorte** [comment]
I think I've set up the github IoLanguage/IoWebsite repo to use the iolanguage.org custom domain and pointed my DNS A records to the proper IPs in the github apex domain instructions. Hopefully the DNS records will update soon and it will start working. In the meantime, the site is down.

**Comment by stevedekorte** [comment]
Ok, looks like DNS is updated and the github site is working. Anything else we need to close this?
