### ISSUE TITLE
Range addon : slice() implementation problems

### ISSUE THREAD

**Issue by dimmie** [stevedekorte/io#64]
Version: pulled io from github today.
Problems:
1. the by parameter is not properly implemented
2. slice uses next, which causes unexpected site-effects (index value modified)
## Patch listed below:

$ diff -Naur stevedekorte-io-c24ec11/addons/Range/io/Range.io io/addons/Range/io/Range.io 
--- stevedekorte-io-c24ec11/addons/Range/io/Range.io    2010-09-03 00:32:06.000000000 +0200
+++ io/addons/Range/io/Range.io 2010-09-16 19:24:35.000000000 +0200
@@ -66,14 +66,16 @@
    //doc Range slice(start, end, [by]) Returns a list containing the values from the Range starting at the start parameter, ending at the end parameter, and optionally incremented by the by parameter.
    slice := method(s, e, b,
        if(e compare(s) < 0, Exception raise("Starting point must be greater than the ending point."))
-       // keep slice without side-effects
-       self = self clone
      if(b isNil, b = 1)
      l := list
      s repeat(self = self next)
      i := s
      while(i <= e,
          l append(value)
-           self = next
-           i = i + 1
-           self = b repeat(self = self next)
-           i = i + b
      )
      l
  )
  ------------------------------------------------------------------------------------------

**Comment by AlesTsurko** [comment]
Trying to dive into it, I've found that:
```Io
Range
r := 0 to(10)
r slice(0,10) //fine
r slice(0,10,3) //Exception: nil does not respond to 'next'
```
As I understand this is the issue?

**Comment by AlesTsurko** [comment]
Looks like this is fixed @stevedekorte

**Comment by stevedekorte** [comment]
Thanks Ales
