### ISSUE TITLE
Problem with Regex when installing via homebrew

### ISSUE THREAD

**Issue by brianjlandau** [stevedekorte/io#68]
The README says to install via homebrew on MacOSX (`brew install io`), but doing so I can't get the Regex Addon to work.

I've installed PCRE via brew also, and it seems to correctly locate it as it does build the Regex addon.

Here's the exception I'm seeing:

```
Exception: Error loading object '/usr/local/Cellar/io/HEAD/lib/io/addons/Regex/_build/dll/libIoRegex.dylib': 'dlopen(/usr/local/Cellar/io/HEAD/lib/io/addons/Regex/_build/dll/libIoRegex.dylib, 10): Library not loaded: /tmp/homebrew-io-HEAD-SIEA/io-build/addons/Range/_build/dll/libIoRange.dylib
Referenced from: /usr/local/Cellar/io/HEAD/lib/io/addons/Regex/_build/dll/libIoRegex.dylib
Reason: image not found'
---------
open                                AddonLoader.io 71
Object Regex                         Command Line 1
```

I've also installed Io on Ubuntu were I have PCRE installed and everything works fine.

If this issue should be filled with the homebrew instead I can do that. But looking at the homebrew formula it looks like it should just work. But ideally if someone has a suggestion for how to get this to work that'll be great, and then we can make the change to the formula.

**Comment by ods94065** [comment]
Note for posterity: I had this problem recently when installing a brew version of Io over an old locally-built version of Io. Cleaning out and redoing the installation with the latest brew (`2013.12.04`) fixed the problem for me:

```sh
brew uninstall io
# the following line doesn't completely uninstall io, but at least
# makes sure the libraries are cleaned up; cleaner approaches welcome!
rm -rf /usr/local/lib/io
brew install io
# because I didn't clean out /usr/local/bin/io and other bits...
brew link --force io
```

**Comment by Moligaloo** [comment]
This problem does still exist in latest version in Mac homebrew.
I resolve it by copy `libIoRange.dylib` to io's `@rpath` 
just by following command:

```bash
DYLIBPATH="/usr/local/Cellar/io/2017.09.06/lib/io/addons/Range/_build/dll/libIoRange.dylib"
RPATH="/usr/local/Cellar/io/2017.09.06/lib"
cp  $DYLIBPATH $RPATH
```

**Comment by AlesTsurko** [comment]
The homebrew version is outdated. We've separated addons from Io. Build Io from source and install the [Regex package](https://github.com/IoLanguage/Regex) using Eerie.
